# Generated by Django 3.1.1 on 2020-10-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(default=None),
        ),
    ]
