# Generated by Django 3.1.1 on 2020-10-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default=None, upload_to='profile_pics'),
        ),
    ]
